local c = require("ash.utils.color")
local p = require("ash.palette")

local function groups(o)
    return {
        ColorColumn = { bg = p.surface0 },
        Conceal = { fg = p.overlay1 },
        Cursor = { fg = p.base, bg = p.text },
        lCursor = { fg = p.base, bg = p.text },
        CursorIM = { fg = p.base, bg = p.text },
        CursorColumn = { bg = p.mantle },
        Directory = { fg = p.blue },
        EndOfBuffer = { fg = p.base },
        ErrorMsg = { fg = p.red, style = { "bold", "italic" } },
        VertSplit = { fg = o.transparent and p.surface1 or p.crust },
        Folded = { fg = p.blue, bg = o.transparent and p.none or p.surface1 },
        FoldColumn = { fg = p.overlay0 },
        SignColumn = { fg = p.surface1 },
        SignColumnSB = { bg = p.crust, fg = p.surface1 },
        Substitute = { bg = p.surface1, fg = p.pink },
        LineNr = { fg = p.surface1 },
        CursorLineNr = { fg = p.lavender },
        MatchParen = { fg = p.peach, bg = p.surface1, style = { "bold" } },
        ModeMsg = { fg = p.text, style = { "bold" } },
        MsgSeparator = {},
        MoreMsg = { fg = p.blue },
        NonText = { fg = p.overlay0 },
        Normal = { fg = p.text, bg = o.transparent and p.none or p.base },
        NormalNC = { fg = p.text, bg = o.transparent and p.none or p.base },
        NormalSB = { fg = p.text, bg = p.crust },
        NormalFloat = { fg = p.text, bg = o.transparent and p.none or p.mantle },
        FloatBorder = { fg = p.blue },
        FloatTitle = { fg = p.subtext0 },
        Pmenu = {
            bg = (o.transparent and vim.o.pumblend == 0) and p.none or c.darken(p.surface0, 0.8, p.crust),
            fg = p.overlay2,
        },
        PmenuSel = { bg = p.surface1, style = { "bold" } },
        PmenuSbar = { bg = p.surface1 },
        PmenuThumb = { bg = p.overlay0 },
        Question = { fg = p.blue },
        QuickFixLine = { bg = p.surface1, style = { "bold" } },
        Search = { bg = c.darken(p.sky, 0.30, p.base), fg = p.text },
        IncSearch = { bg = c.darken(p.sky, 0.90, p.base), fg = p.mantle },
        CurSearch = { bg = p.red, fg = p.mantle },
        SpecialKey = { link = "NonText" },
        SpellBad = { sp = p.red, style = { "undercurl" } },
        SpellCap = { sp = p.yellow, style = { "undercurl" } },
        SpellLocal = { sp = p.blue, style = { "undercurl" } },
        SpellRare = { sp = p.green, style = { "undercurl" } },
        StatusLine = { fg = p.text, bg = o.transparent and p.none or p.mantle },
        StatusLineNC = { fg = p.surface1, bg = o.transparent and p.none or p.mantle },
        TabLine = { bg = p.crust, fg = p.overlay0 },
        TabLineFill = { bg = o.transparent and p.none or p.mantle },
        TabLineSel = { link = "Normal" },
        TermCursor = { fg = p.base, bg = p.rosewater },
        TermCursorNC = { fg = p.base, bg = p.overlay2 },
        Title = { fg = p.blue, style = { "bold" } },
        Visual = { bg = p.surface1, style = { "bold" } },
        VisualNOS = { bg = p.surface1, style = { "bold" } },
        WarningMsg = { fg = p.yellow },
        Whitespace = { fg = p.surface1 },
        WildMenu = { bg = p.overlay0 },
        WinBar = { fg = p.rosewater },
        WinBarNC = { link = "WinBar" },
        WinSeparator = { fg = o.transparent and p.surface1 or p.crust },
    }
end

return groups
