local c = require("ash.utils.color")
local p = require("ash.palette")

local function groups(o)
    return {
        SagaTitle = { fg = p.teal, style = { "bold" } },
        SagaBorder = { fg = p.blue, bg = p.none },
        SagaNormal = { bg = o.transparent and p.none or p.base },
        SagaToggle = { fg = p.green },
        SagaCount = { fg = p.overlay1 },
        SagaBeacon = { bg = c.darken(p.surface0, 0.8, p.crust) },
        SagaVirtLine = { fg = p.surface2 },
        SagaSpinner = { fg = p.mauve, style = { "bold" } },
        SagaSpinnerTitle = { fg = p.mauve, style = { "bold" } },
        SagaText = { fg = p.text },
        SagaSelect = { fg = p.blue, style = { "bold" } },
        SagaSearch = { link = "Search" },
        SagaFinderFname = { fg = p.subtext0, style = { "bold" } },
        ActionFix = { fg = p.pink },
        ActionPreviewTitle = { fg = p.mauve, bg = o.transparent and p.none or p.base },
        CodeActionText = { fg = p.green },
        CodeActionNumber = { fg = p.pink },
        SagaImpIcon = { fg = p.pink },
        SagaLightBulb = { link = "DiagnosticSignHint" },
        RenameNormal = { fg = p.text },
        RenameMatch = { link = "Search" },
        DiagnosticText = { fg = p.text },
        SagaWinbarSep = { fg = p.flamingo },
        SagaDetail = { link = "Comment" },
        SagaFileName = { fg = p.overlay2, style = { "bold" } },
        SagaFolderName = { fg = p.overlay2, style = { "bold" } },
        SagaInCurrent = { fg = p.peach },

        -- Lspkind icons support
        LspKindClass = { fg = p.yellow },
        LspKindConstant = { fg = p.peach },
        LspKindConstructor = { fg = p.sapphire },
        LspKindEnum = { fg = p.yellow },
        LspKindEnumMember = { fg = p.teal },
        LspKindEvent = { fg = p.yellow },
        LspKindField = { fg = p.teal },
        LspKindFile = { fg = p.rosewater },
        LspKindFunction = { fg = p.blue },
        LspKindInterface = { fg = p.yellow },
        LspKindKey = { fg = p.red },
        LspKindMethod = { fg = p.blue },
        LspKindModule = { fg = p.blue },
        LspKindNamespace = { fg = p.blue },
        LspKindNumber = { fg = p.peach },
        LspKindOperator = { fg = p.sky },
        LspKindPackage = { fg = p.blue },
        LspKindProperty = { fg = p.teal },
        LspKindStruct = { fg = p.yellow },
        LspKindTypeParameter = { fg = p.blue },
        LspKindVariable = { fg = p.peach },
        LspKindArray = { fg = p.peach },
        LspKindBoolean = { fg = p.peach },
        LspKindNull = { fg = p.yellow },
        LspKindObject = { fg = p.yellow },
        LspKindString = { fg = p.green },
        -- ccls-specific icons
        LspKindTypeAlias = { fg = p.green },
        LspKindParameter = { fg = p.blue },
        LspKindStaticMethod = { fg = p.peach },
        -- Microsoft-specific icons
        LspKindText = { fg = p.green },
        LspKindSnippet = { fg = p.mauve },
        LspKindFolder = { fg = p.blue },
        LspKindUnit = { fg = p.green },
        LspKindValue = { fg = p.peach },
    }
end

return groups
